const prefix = 'R3-GO/SESSION/'
export const LOGIN_FORM_ACTION_PREFIX = `${prefix}LOGIN`
export const LOGIN_REQUEST = `${prefix}LOGIN_REQUEST`
export const LOGIN_SUCCESS = `${prefix}LOGIN_SUCCESS`
export const LOGIN_FAILURE = `${prefix}LOGIN_FAILURE`
export const LOGOUT_REQUEST = `${prefix}LOGOUT_REQUEST`
export const LOGOUT_SUCCESS = `${prefix}LOGOUT_SUCCESS`
export const LOGOUT_ERROR = `${prefix}LOGOUT_ERROR`
export const READ_SESSION_COOKIE = `${prefix}READ_SESSION_COOKIE`
export const TOGGLE_SESSION_FORM_DELAY = `${prefix}TOGGLE_SESSION_FORM_DELAY`
export const TOGGLE_SESSION_FORM = `${prefix}TOGGLE_SESSION_FORM`
